version: '3'        #Docker compose version
services:
  yolo_app:
    container_name: yolo_app
    build: 
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - yolo_backend
    ports : 
      - '3000:3000'
    networks:
      - yolo_network

  yolo_backend:
    container_name: yolo_backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - yolo_db
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://yolo_db:27017
      DB_NAME: yolomy
    networks:
      - yolo_network  

  yolo_db:
    container_name: yolo_db
    image : mongo:4.2.15
    environment:
      MONGO_INITDB_ROOT_USERNAME: yolo
      MONGO_INITDB_ROOT_PASSWORD: yolo123
    volumes:
      - mongo_data:/data/db
    networks:
      - yolo_network

volumes:
  mongo_data: {}

networks:
  yolo_network:
    driver: bridge
