version: '3.4'        #Docker compose version
services:
  yolo_app:
    container_name: yolo_app
    build: ./client
    depends_on:
      - yolo_backend
    ports : 
      - '3000:3000'
    networks:
      - yolo_network
    tty: true         # Allow app to run in the backgroud
    
  yolo_backend:
    container_name: yolo_backend
    build: ./backend
    environment:
      MONGODB_URI: mongodb://yolo_db:27017/yolomy
    ports:
      - 4000:4000
    depends_on:
      - yolo_db
    networks:
      - yolo_network  

  yolo_db:
    container_name: yolo_db
    image : mongo:latest
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/home/devops05/data/yolo
    environment: 
      MONGODB_INITDB_ROOT_USERNAME: username
      MONGODB_INITDB_ROOT_PASSWORD: password
    networks:
      - yolo_network

volumes:
  mongo_data:

networks:
  yolo_network:
    driver: bridge