# Application Servers
[client]
127.0.0.1

# Database server
[db]
127.0.0.1

# Group 'multi' with all servers
[multi:children]
client
db

# Variavle tat wil be applier to all servers
[multi:vars]
ansible_ssh_user=vagrant
ansible_ssh_private_key_file = ~/.vagrant.d/insecure_private_key

ansible_ssh_common_args='-o StrictHostKeyChecking=no'
