---
- hosts: all
  become: yes
  roles:
    - common_roles
    - docker
    - app
  tasks:
    - name: Build and run Docker Compose
      shell: docker-compose up -d
      args:
        chdir: /vagrant/app