- hosts: localhost
  tasks: 
   - name: Configuring Docker Repository
     yum_repository:
       name: Docker
       description: "Docker Repo"
       baseurl: "https://download.docker.com/linux/centos/docker-ce.repo" 
       gpgcheck: no
     register: x

   - name: Checking Configuration Status
     debug:
       var: x.failed

   - name: Installing Docker
     package:
       name: "docker-ce-18.06.3.ce-3.el7.x86_64"
       state: present
     register: y

   - name: Checking Install Status
     debug:
       var: y.failed

   - name: Starting Docker Daemon
     service:
       name: docker
       state: started
       enabled: yes
     when: y.failed == false

   - name: Install
     command: "pip install docker-py"    

   - name: Pull a Docker Image Yolo App
     docker_image: 
        name: jgituiku/yolo_yolo_app
        tag: v3
        source: pull
     register: z
   - name: Checking Pull Status
     debug: 
       var: z

   - name: Pull a Docker Image Yolo Backend
     docker_image: 
        name: jgituiku/yolo_yolo_backend
        tag: v1
        source: pull
     register: z
   - name: Checking Pull Status
     debug: 
       var: z

   - name: Creating a Persistent Volume Dir
     file:
       path: "/root/yolo"
       state: directory

   - name: Copying the Yolo client in the Directory
     copy: 
       src: "/devops05/yolo/client"
       dest: "/root/yolo"

   - name: Copying the Yolo backend in the Directory
     copy:        
       src: "/devops05/yolo/backend"
       dest: "/root/yolo"

   - name: Launching an Backend Container
     when: z.failed == false
     docker_container:
       name: Yolo Backend
       image: yolo_yolo_backend
       state: started
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
       volumes: 
         - /root/yolo:/usr/local/apache2/htdocs

   - name: Launching an Client Container
     when: z.failed == false
     docker_container:
       name: Yolo Client
       image: yolo_yolo_app
       state: started
       exposed_ports:
         - "80"
       ports:
         - "8888:80"
       volumes: 
         - /root/yolo:/usr/local/apache2/htdocs