---
services:
  - type: web
    name: yolo_app
    env: docker
    plan: starter
    dockerfilePath: ./client/Dockerfile
    envVars:
      - key: PORT
        value: 3000
    healthCheckPath: /
  - type: web
    name: yolo_backend
    env: docker
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        value: mongodb://yolo_db:27017/
    healthCheckPath: /
  databases:
    - name: yolo_db
     env: docker
     plan: starter
     dockerfilePath: ./db/Dockerfile
     envVars:
       - key: PORT
         value: 27017