---
# tasks file for docker_compose
- name: Ensure apt transport is installed
  apt:
    name: apt-transport-https
    state: present
    update_cache: yes

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    state: present
    update_cache: yes

- name: Ensure Docker is installed
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Install Docker Python module
  pip:
    name: docker
    state: present

- name: Create Docker network
  community.docker.docker_network:
    name: "{{ yolo_network }}"
    driver: bridge

- name: Create a Docker volume for MongoDB data
  community.docker.docker_volume:
    name: "{{ mongo_data_volume }}"

- name: Build and start yolo_db container
  community.docker.docker_container:
    name: yolo_db
    image: "{{ mongo_image }}"
    ports:
      - "27017:27017"
    volumes:
      - "{{ mongo_data_volume }}:/data/db"
    networks:
      - name: "{{ yolo_network }}"
    state: started
    restart_policy: always

- name: Build and start yolo_backend container
  community.docker.docker_container:
    name: yolo_backend
    build:
      path: ./backend
    environment:
      MONGODB_URI: "{{ mongodb_uri }}"
    ports:
      - "5000:5000"
    depends_on:
      - yolo_db
    networks:
      - name: "{{ yolo_network }}"
    state: started

- name: Build and start yolo_app container
  community.docker.docker_container:
    name: yolo_app
    build:
      path: ./client
    ports:
      - "3000:3000"
    depends_on:
      - yolo_backend
    networks:
      - name: "{{ yolo_network }}"
    tty: true
    state: started
